name: Build Caddy-Trojan


on: 
    workflow_dispatch:
    push:

jobs:
  build-caddy-trojan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
        go-version: [ '1.22.x' ]
    

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: |
            **/go.sum
    
      - name: Build Xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
    
      - name: Build Caddy-Trojan
        run: |
          mkdir -p ~/output
          xcaddy build --with github.com/imgk/caddy-trojan --output ~/output/caddy
          tar -czvf caddy-trojan_${{ matrix.os }}_${{ matrix.arch }}.tar.gz ~/output/caddy
          
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            ~/output/caddy-trojan_${{ matrix.os }}_${{ matrix.arch }}.tar.gz