name: Go CI


on: 
    workflow_dispatch:
    push:

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
        go-version: [ '1.22.x' ]
        path: ./caddy-trojan
    

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
    
      - name: Build Xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
    
      - name: Build with xcaddy
        run: xcaddy build --with github.com/imgk/caddy-trojan --output ${{ matrix.path }}
        
      - name: Publish Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: caddy-trojan_${{ matrix.os }}_go${{ matrix.go-version }}_${{ matrix.arch }}
          path: ${{ matrix.path }}