name: Check


on: 
    workflow_dispatch:
    schedule:
      - cron: '30 2 5 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check And Commit
      run: |
        sudo apt update -y
        sudo apt install jq -y
        chmod +x update_sha.sh
        ./update_sha.sh

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.TOKEN }}
         branch: main